### ISSUE TITLE
No implicit conversion from const char* to String<char8> allowed

### ISSUE THREAD

**Issue by Lehks** [Lehks/NostraUtils#10]
The string does not allow code like this:
`NOU::NOU_DAT_ALG::String<char8> str = "Hello World!";`

This is most likely due to the absence of a constructor that task a const char8* as a parameter. Allthough not testet, this issue should also be present for any other string instance (like an instance that uses char16 or char32).

**Comment by NooCi** [comment]
6a1f3aadeb4ebe31164b6f7ace8016c8e77f5984
