### ISSUE TITLE
Functionality to delete a file

### ISSUE THREAD

**Issue by Lehks** [Lehks/NostraUtils#36]
File: file_mngt/File.hpp

The file class lacks a feature to delete it.

**Comment by xC0rp** [comment]
+functionallity to determine filesize

**Comment by xC0rp** [comment]
still needs testing on Linux/mac

- [ ] Linux

- [ ] MacOS

**Comment by xC0rp** [comment]
The File Class should be in a working state in commit b95d700aa83608fe247433c19cdd810d449d19ea
but it'S still dependant on #38

**Comment by xC0rp** [comment]
Merged into (develop)[https://github.com/Lehks/NostraUtils/tree/develop]
