### ISSUE TITLE
Make path seperators independant in the constructor.

### ISSUE THREAD

**Issue by LeslieM98** [Lehks/NostraUtils#47]
When using th Path class, executing following code on Windows:
`NOU::NOU_FILE_MNGT::Path p("C:\\Users\\Leslie\\Desktop\\NOMatTestFiles\\test");`
`std::cout << p.getAbsolutePath().rawString() << std::endl;`
produces the result `C:\Users\Leslie\Desktop\NOMatTestFiles\test`

where
`NOU::NOU_FILE_MNGT::Path p("C:/Users/Leslie/Desktop/NOMatTestFiles/test");`
`std::cout << p.getAbsolutePath().rawString() << std::endl;`
produces following result: `D:\Repos\NostraUtils\C:\Users\Leslie\Desktop\NOMatTestFiles\test`

It seems to me that the Path class just appends to the current working directory, in my case `D:\Repos\NostraUtils`

**Comment by xC0rp** [comment]
Still needs fixing for Posix

**Comment by xC0rp** [comment]
Fixed for Unix/Linux in 53a2781ede7301738fe296b9936320a795b3b5e6
