### ISSUE TITLE
Hash Funktion issue

### ISSUE THREAD

**Issue by NooCi** [Lehks/NostraUtils#5]
There is probably an issue with the Hash funktion. The Hash map, wich uses this funktion, has a change to crash due to violate reading location. (My be the hash value is not alwasy the same).

To force this problem to show, simply pull the newest Map branche and execute the program. There will be an error in the main function.

**Comment by HELLSCORPION** [comment]
Fixed in abf1be448ed190aba3721b7fee2ebccdd7d42196
