### ISSUE TITLE
String.trim() does not work properly

### ISSUE THREAD

**Issue by LeslieM98** [Lehks/NostraUtils#65]
String.trim() also removes spaces within a string and not like stated only at the beginning and end.

    NOU::NOU_DAT_ALG::String8 test = " a 123";
    test.trim();
    std::cout << test.rawStr() << std::endl;

Expected result:
`a 123`
Recieved result:
`a123`

**Comment by NooCi** [comment]
ff9f61f721509066753869975163bb7c876a29ba
