### ISSUE TITLE
NOU::NOU_FILE_MNGT::Path::operator + not behaving properly

### ISSUE THREAD

**Issue by Lehks** [Lehks/NostraUtils#66]
File: file_mngt/Path.hpp / file_mngt/Path.cpp

The operator(s) + do not have the correct signature and behavior. Currently they behave the same way as += does, while they are actually supposed to return a new instance. Also, they should be marked _const_.

**Comment by NooCi** [comment]
e0df9207fd61407bbc0882a21fa622ed0ed05af4
