### ISSUE TITLE
NOU::NOU_FILE_MNGT::Path::operator += only updating the absolute path.

### ISSUE THREAD

**Issue by Lehks** [Lehks/NostraUtils#67]
File: file_mngt/Path.hpp / file_mngt/Path.cpp

All variants of the operators + and += only set the value of the absolute path which may result in a wrong value for the other atributes (e.g. the relative path) if the latter ones were already evaluted before the change of the absolute path takes place. This may be solved by forcing the re-evaluation of all of the attributes after the operator += was called.

**Comment by NooCi** [comment]
e0df9207fd61407bbc0882a21fa622ed0ed05af4
