### ISSUE TITLE
String concat() compile error

### ISSUE THREAD

**Issue by Lehks** [Lehks/NostraUtils#8]
Calling String::concat(...) (any of the overloads) will produce compile the error C2663 with the message "'nostra::utils::dat_alg::String<nostra::utils::char8>::append': 8 overloads have no legal conversion for 'this' pointer".

Also, it seems that the implementation of the concat() methods does not make sense, as it will first create an empty string, then call this->append() with the object that the string should be concatenated with and then returns this->copy().

**Comment by NooCi** [comment]
ad68d25d5281ba04ffbb447ad4d6ffc65784bc38
